export const LOAD_ALL_ISSUES_SUCCESS = 'LOAD_ALL_ISSUES';
export const DELETE_ISSUE_SUCCESS = 'DELETE_ISSUE';
export const ADD_ISSUE_SUCCESS = 'ADD_ISSUE';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS';
export const EDIT_ISSUE_SUCCESS = 'EDIT_ISSUE_SUCCESS';